version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f localhost:3000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 5
    ports:
      - "3000:3000"
    environment:
      - ENVIORNMENT=production
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=swappable
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=swappable
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U swappable"]
      interval: 30s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
